<?php
/**
 * DO NOT EDIT THIS FILE
 *
 * Define the path to your wp-tests-config.php using the PHPUNIT_WORDPRESS__TESTS_CONFIG environment variable.
 */

/**
 * Load the real wp-tests-config.php, wherever it may be.
 */
if ( file_exists( getenv( 'PHPUNIT_WORDPRESS__TESTS_CONFIG' ) ) ) {
    require getenv( 'PHPUNIT_WORDPRESS__TESTS_CONFIG' );
}

/**
 * $table_prefix must be defined as a local variable here as expected by the library's bootstrap.php.
 */
if ( false !== getenv( 'PHPUNIT_WORDPRESS__TABLE_PREFIX' ) ) {
    $table_prefix = getenv( 'PHPUNIT_WORDPRESS__TABLE_PREFIX' );
} elseif ( ! isset( $table_prefix ) ) {
    $table_prefix = 'wptests_';
}
