name: Update from WordPress Develop Repository

on:
  push:
    branches:
      - development # Adjust the branch name as needed
  schedule:
    - cron: '0 * * * *'

jobs:
  update-source-code-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone the WordPress Develop repository
        run: git clone git://develop.git.wordpress.org/ source --quiet

      - name: Copy the necessary files to the root directory
        run: |
          cp -r source/tests/phpunit/data/* data
          cp -r source/tests/phpunit/includes/* includes
          cp -r source/tests/phpunit/multisite.xml multisite.xml
          cp -r source/tests/phpunit/wp-mail-real-test.php wp-mail-real-test.php
          cp -r source/wp-tests-config-sample.php wp-config-sample.php

      - name: Remove the source directory
        run: rm -rf "source"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: Update from WordPress Develop
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: main
          delete-branch: true
          title: 'Update from WordPress Develop Repository'
          body: |
            This PR updates the codebase with the latest changes from the WordPress Develop repository
            - Update from WordPress Develop Repository
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            update
            automated pr
          draft: false

      - name: Check Output
        run: |
          echo "Pull Request created successfully!"
