name: Update from WordPress Develop Repository

on:
  push:
    branches:
      - development # Adjust the branch name as needed
  schedule:
    - cron: '0 * * * *'

jobs:
  update-source-code-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          # Set up user information
          git config --global user.email "34349365+mralaminahamed@users.noreply.github.com"
          git config --global user.name "Al Amin (Bot)"

          # Set up remote url
          git remote set-url origin "https://${{ secrets.PERSONAL_TOKEN }}@github.com/mralaminahamed/phpunit-wordpress-tests.git"

          # Create a new branch
          branch_name="update/sync-from-wordpress-develop-repo"
          git checkout -b "$branch_name"

          # Clone the WordPress Develop repository
          git clone git://develop.git.wordpress.org/ source --quiet

          # Copy the necessary files to the root directory
          cp -r source/tests/phpunit/data/* data
          cp -r source/tests/phpunit/includes/* includes
          cp -r source/tests/phpunit/multisite.xml multisite.xml
          cp -r source/tests/phpunit/wp-mail-real-test.php wp-mail-real-test.php
          cp -r source/wp-tests-config-sample.php wp-config-sample.php

          # Remove the source directory
          rm -rf "source"

          # Add and commit the changes to the new branch
          git add ./
          git commit -m "Update from WordPress Develop"

          # Push the new branch to the remote repository
          git push --set-upstream origin "$branch_name"

          # Create a new pull request
          gh pr create --base main --head "$branch_name" --title "Update from WordPress Develop" --body "This PR updates the codebase with the latest changes from the WordPress Develop repository"

      - name: Check Output
        run: |
          echo "Pull Request created successfully!"
