name: Update from WordPress Develop Repository

on:
  push:
    paths:
      - ".github/workflows/update.yml"
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-source-code-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config core.autocrlf false
          git config core.eol lf

      - name: Clone the WordPress Develop repository
        run: |
          git clone --depth 1 https://github.com/WordPress/wordpress-develop.git source
          cd source
          git config core.autocrlf false
          git config core.eol lf

      - name: Copy the necessary files to the root directory
        run: |
          rsync -avz --delete --exclude='.gitattributes' source/tests/phpunit/data/ data/
          rsync -avz --delete source/tests/phpunit/includes/ includes/
          cp -f source/tests/phpunit/multisite.xml multisite.xml
          cp -f source/tests/phpunit/wp-mail-real-test.php wp-mail-real-test.php
          cp -f source/wp-tests-config-sample.php wp-config-sample.php

      - name: Remove the source directory
        run: rm -rf "source"

      - name: Normalize line endings
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          find . -type f -not -path './.git/*' -print0 | xargs -0 dos2unix

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Update from WordPress Develop Repository and normalize line endings" || echo "No changes to commit"

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: Update from WordPress Develop Repository and normalize line endings
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-from-wp-develop
          delete-branch: true
          title: 'Update from WordPress Develop Repository and normalize line endings'
          body: |
            This PR updates the codebase with the latest changes from the WordPress Develop repository and normalizes line endings.

            Changes include:
            - Updated files in `data/` and `includes/` directories
            - Updated `multisite.xml`, `wp-mail-real-test.php`, and `wp-config-sample.php`
            - Normalized line endings to LF for all files

            This update was automatically generated by the GitHub Actions workflow.
          labels: |
            update
            automated pr
          assignees: mralaminahamed
          draft: false

      - name: Check Output
        if: steps.git-check.outputs.changes == 'true'
        run: echo "Pull Request created successfully!"

      - name: No changes detected
        if: steps.git-check.outputs.changes != 'true'
        run: echo "No changes detected. Skipping PR creation."
